- name: Restart httpd service
  service:
    name: httpd
    state: restarted

- name: Give permission to directory
  file:
    path: '{{ site_directory }}'
    state: directory
    mode: '0755'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    recurse: yes