---
- name: Setup for the firewall
  hosts: webserver
  become: yes
  tasks:
  - name: Start Firewalld service
    service:
      name: firewalld
      state: started
      enabled: yes
  # Enable the port specified in the webserver variables
  - name: Enable service for the specified port
    firewalld:
      port: '{web_port}/tcp'
      permanent: yes
      immediate: yes
      state: enabled
      zone: public
    notify:
    - Restart firewalld service
  # Restart firewalld for each modification
  handlers:
    - name: Restart firewalld service
      service:
        name: firewalld
        state: restarted
