- name: Generate keys pair and deactivate SSH Pass
  hosts: all
  gather_facts: False
  roles:
  - ssh-key-generator

- name: Setup httpd server
  hosts: webserver
  become: yes
  gather_facts: false
  roles:
  - httpd-server
  - python-cgi

- name: Setup httpd server
  hosts: dbserver
  become: yes
  gather_facts: false
  roles:
  - db-server
  - create-mysql-db
