- name: Setup httpd server
  hosts: webserver
  become: yes
  gather_facts: false
  roles:
  - httpd-server

- name: Setup httpd server
  hosts: dbserver
  become: yes
  gather_facts: false
  roles:
  - db-server