# -*- mode: ruby -*-
# vi: set ft=ruby :
# To enable zsh, please set ENABLE_ZSH env var to "true" before launching vagrant up 
#   + On windows => $env:ENABLE_ZSH="true"
#   + On Linux  => export ENABLE_ZSH="true"

Vagrant.configure("2") do |config|
  # clients=4
  # ram_client=2048
  # cpu_client=1
  # (1..clients).each do |i|
  #   config.vm.define "client#{i}" do |client|
  #     client.vm.box = "bento/rockylinux-8.6"
  #     client.vm.network "private_network", type: "static", ip: "192.190.70.1#{i}"
  #     client.vm.hostname = "client#{i}"
  #     client.vm.provider "virtualbox" do |v|
  #       v.name = "client#{i}"
  #       v.memory = ram_client
  #       v.cpus = cpu_client
  #     end
  #   end
  #   config.vm.box_download_insecure=true
  # end
  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "bento/rockylinux-8.6"
    ansible.vm.network "private_network", type: "static", ip: "192.190.70.111"
    ansible.vm.hostname = "ansible"
    ansible.vm.provider "virtualbox" do |v|
      v.name = "ansible"
      v.memory = 2048
      v.cpus = 1
    end
    config.vm.provision "file", source: "../.vault_password.txt" , destination: "/home/vagrant/.vault_password.txt"

    # ansible.vm.provision :shell do |shell|
    #     shell.path = "install_ansible.sh"
    # end
  end
end
