---
- name: My first site
  hosts: webserver
  become: yes
  tasks:
  # Install python3 and pip dependancies
  - name: Install python39 and mysql dependancies
    dnf:
      name: '{{ item }}'
      state: present
    with_items: ['git','python39','python39-PyMySQL']

  - name: Install pymysql
    pip:
      name: pymysql
  # Setup the conf file with the symbolic link
  - name: test copy files
    copy:
      src: /home/devops/its_project_a/myFirstSite
      dest: /etc/httpd/sites-availables/myfirstSite

  - name: test symbolic link
    file:
      src: /etc/httpd/sites-availables/myfirstSite
      dest: /etc/httpd/sites-enabled/myfirstSite.conf
      state: link

  - name: test git repo
    git:
      repo: https://github.com/sofackj/python-cgi.git
      dest: /var/www/html/
      single_branch: yes
      version: test-python-cgi
      force: yes
    notify:
    - Give permission to /var/www/html
    - Restart httpd service

  handlers:
  - name: Restart httpd service
    service:
      name: httpd
      state: restarted

  - name: Give permission to /var/www/html
    file:
      path: /var/www/html
      state: directory
      mode: '0755'
      recurse: yes